### ISSUE TITLE
Add notebook to dandi example notebooks?

### ISSUE THREAD

**Issue by rly** [mesoscale-activity-map/map-ephys#266]
Hi @kushalbakshi and map-ephys maintainers, would one of you be willing to add this notebook https://github.com/mesoscale-activity-map/map-ephys/blob/master/notebook/browse_dandisets.ipynb demonstrating how to explore an NWB file from dandiset 000363 to the [DANDI example-notebooks repo](https://github.com/dandi/example-notebooks)? That way, it would be accessible by anyone who uses the dandihub and it would help any first-time users of this dandiset quickly learn how to access and plot the data. 

To add a new notebook, create a PR according to the instructions in the README. I could also create the PR if you would prefer. 

Thanks!

**Comment by kushalbakshi** [comment]
Hi @rly, thank you for reminding me about this. I'll add this to my backlog and should be able to get to it by the end of next week and get the PR created
