### ISSUE TITLE
visualization mesh: move to / load from consistent 'reference' location

### ISSUE THREAD

**Issue by ixcat** [mesoscale-activity-map/map-ephys#86]
should move into some data area, load function should read from here

**Comment by ttngu207** [comment]
`AnnotatedBrainSurface` in fact already shipped with a load function `load_matlab_mesh`. 
Thus, really we can just remove the automatic loading (from hard-code path) from `shell.ccfload` - this line:
```
    ccf.AnnotatedBrainSurface.load_matlab_mesh('Annotation_new_10_ds222_16bit_isosurf.mat')
```
In the case where we might have a new surf, we can just do: 
```
AnnotatedBrainSurface.load_matlab_mesh('path_to_the_mat_file`)
```
